name: Deploy MLFlow Server

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

  REPOSITORY: ${{ secrets.REPOSITORY }}
  DEPLOY_NAME: ${{ secrets.DEPLOY_NAME }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        name: Authenticate To GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          
      - name: Docker Config
        run:
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
            
      - name: Build Image
        run:
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/mlflow:${{ github.sha }} .

      - name: Push Image
        run:
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/mlflow:${{ github.sha }}
            
      - name: Deploy To Cloud Run
        run: |
          gcloud run deploy ${{ env.DEPLOY_NAME }} \
          --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/mlflow:${{ github.sha }} \
          --region=${{ env.REGION }} \
          --update-secrets=POSTGRESQL_URL=database_url:latest \
          --update-secrets=STORAGE_URL=bucket_url:latest \
          --allow-unauthenticated \
          --port=5000
            